CREATE DATABASE robooks;

USE robooks;

CREATE TABLE livros (
    LIVRO_ID INT PRIMARY KEY AUTO_INCREMENT NOT NULL,
    LIVRO_TITULO VARCHAR(150) NOT NULL,
    LIVRO_N_AUTOR VARCHAR(100) NOT NULL,
    LIVRO_S_AUTOR VARCHAR(100) NOT NULL,
    LIVRO_GENERO VARCHAR(100) NOT NULL,
    LIVRO_QTD INT NOT NULL,
    LIVRO_ISBN BIGINT NOT NULL,
    LIVRO_PRATELEIRA VARCHAR(10),
    LIVRO_DATALANC DATE,
    LIVRO_PRECO DECIMAL(10,2)
);

-- CRIANDO A TABELA DE CLIENTES
CREATE TABLE clientes(
    CLIENTE_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    CLIENTE_CPF BIGINT NOT NULL,
    CLIENTE_NOME VARCHAR(100) NOT NULL,
    CLIENTE_LOGRADOURO VARCHAR(100),
    CLIENTE_COMPLEMENTO VARCHAR(100) NULL,
    CLIENTE_BAIRRO VARCHAR(100),
    CLIENTE_CIDADE VARCHAR(100),
    CLIENTE_CEP VARCHAR(15),
    CLIENTE_UF CHAR(2),
    CLIENTE_TEL1 BIGINT NOT NULL,
    CLIENTE_TEL2 VARCHAR(15),
    CLIENTE_DATANASC DATE NOT NULL,
    CLIENTE_DATACAD DATETIME
);


-- CRIANDO A TABELA DE VENDAS
CREATE TABLE vendas(
    VENDA_ID INT NOT NULL AUTO_INCREMENT PRIMARY KEY,
    VENDA_DATAHORA DATETIME NOT NULL,
    VENDA_QTD INT NOT NULL,
    VENDA_FRMPAG VARCHAR(20) NOT NULL,
    VENDA_TOTAL DECIMAL(10.2) NOT NULL,
    VENDA_SUBTOTAL DECIMAL(10.2) NOT NULL,
    VENDA_FK_LIVRO_ID INT NOT NULL,
    VENDA_FK_CLIENTE_ID INT NOT NULL
);

-- RELACIONANDO TABELAS HORA DE SHIPAR

-- LIVRO E VENDAS
ALTER TABLE vendas ADD CONSTRAINT VENDA_LIVRO FOREIGN KEY (VENDA_FK_LIVRO_ID)
REFERENCES livros (LIVRO_ID);

-- CLIENTE E VENDAS
ALTER TABLE vendas ADD CONSTRAINT VENDA_CLIENTE FOREIGN KEY (VENDA_FK_CLIENTE_ID)
REFERENCES clientes (CLIENTE_ID);