-- ESTE É UM COMENTÁRIO

-- INSERINDO LIVROS NA MINHA TABELA. (LINHA A LINHA)
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) VALUES ("Guerra dos Tronos", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);


-- INSERINDO LIVROS NA MINHA TABELA. (LINHA MULTILINHAS)
-- ULTIMA LINHA DEVERÁ CONTER O ; NO FINAL APÓS O ULTIMO PARENTESES
INSERT INTO livros ( LIVRO_TITULO, LIVRO_N_AUTOR, LIVRO_S_AUTOR, LIVRO_GENERO, LIVRO_ISBN, LIVRO_PRATELEIRA, LIVRO_DATALANC, LIVRO_PRECO) 
VALUES
    ("Harry Potter", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45),
    ("hahaha", "blala", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45),
    ("biriri", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45),
    ("XPTO", "George R.R.", "Martin", "Morte", 978123456789, "16", "1900-04-01", 60.45);

--------------------------------------------------------------------------------------------------------------------------------------------------------

-- FAZENDO VENDAS HUEHUEHUE
INSERT INTO vendas (VENDA_DATAHORA, VENDA_QTD, VENDA_FRMPAG, VENDA_TOTAL, VENDA_SUBTOTAL,
VENDA_FK_LIVRO_ID, VENDA_FK_CLIENTE_ID)
VALUES
("2025-03-12-10:59:00", 1, "CARTÃO", 120.00, 120.00, 5, 5 );
UPDATE livros SET LIVRO_QTD = 9 WHERE LIVRO_ID = 5;


-- MODO QUEBRANDO LINHAS
-- CRIANDO CLIENTE NA TABELA
INSERT INTO clientes (
    CLIENTE_NOME,
    CLIENTE_CPF,
    CLIENTE_LOGRADOURO,
    CLIENTE_COMPLEMENTO,
    CLIENTE_CIDADE,
    CLIENTE_CEP,
    CLIENTE_UF,
    CLIENTE_DATACAD,
    CLIENTE_DATANASC,
    CLIENTE_TEL1
)
VALUES(
    "Michael Toniolo",
    56823889888,
    "Minha rua",
    "Minha Casa",
    "Condado de Brodowski",
    "14340000",
    "SP",
    "2024-03-12-09:45:55",
    "1992-01-25",
    "16992530477"
);


------------------------------------------------------------------------
-- UPDATE DE DADOS
UPDATE clientes SET CLINETE_TEL1 = "16992530477" WHERE CLIENTE_ID = 3;

-- UPDATE LIVROS PARA QTD
UPDATE livros SET LIVRO_QTD = '10';

--------------------------------------------------------------------------------------------
-- ALTERANDO TIPO DE DADO DE UMA COLUNA
ALTER TABLE clientes MODIFY COLUMN CLIENTE_TEL1 BIGINT;

-- ADICIONANDO NOVA COLUNA EM UMA TABELA (LEMBRANDO QUE COLUNA VIRA VAZIA)
ALTER TABLE livros ADD COLUMN LIVRO_QTD INT NOT NULL;

-- ALTERANDO NOME DA COLUNA
ALTER TABLE clientes CHANGE CLINETE_NOME CLIENTE_NOME VARCHAR(100);

-- EXLUINDO UMA TABELA
ALTER TABLE clientes DROP COLUMN CLIENTE_TEL2;

--  ########################################################################

-- O MUNDO DOS SELECTS (PESQUISAS, PERGUNTAS)

-- LISTA TODAS AS BASES DE DADOS
SHOW DATABASES;

-- LISTA TODAS AS TABELAS
USE robooks;
SHOW TABLES;

-- LISTA TODAS AS COLUNAS DE UMA TABELA
USE robooks;
DESC clientes;

-- LISTA TODOS OS DADOS DE UMA TABELA OU MAIS...
USE robooks;
SELECT * FROM clientes;

-- TRAZ SOMENTE O ENDEREÇO DO CLIENTE
USE robooks;
SELECT CLIENTE_LOGRADOURO FROM clientes;

-- TRAZ O ENDEREÇO DE UM CLIENTE ESPECÍFICO
USE robooks;
SELECT CLIENTE_LOGRADOURO, CLIENTE_TEL1 FROM clientes WHERE CLIENTE_NOME = "Michael";

-- PESQUINA NOME E ENDEREÇO DO CLIENTE COM COMPRA COM PERFUMARIA NO LOGRADOURO
SELECT CLIENTE_NOME, CLIENTE_LOGRADOURO AS 'ENDEREÇO DO CLIENTE', CLIENTE_COMPLEMENTO, CLIENTE_BAIRRO, CLIENTE_CEP, CLIENTE_CIDADE 
FROM vendas 
INNER JOIN clientes ON VENDA_FK_CLIENTE_ID = CLIENTE_ID;



